name: Python Rep Workflow

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
        architecture: 'x64'
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 test/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 test/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run py script
      run: |
        python test/test_wk.py
