$(NAME)

CC=gcc

CFLAGS=-Wall -Wextra -Werror

SRC=my_atoi.c my_bzero.c my_calloc.c my_isalnum.c my_isalpha.c my_isascii.c my_isdigit.c \
my_isprint.c my_memchr.c my_memcmp.c my_memcpy.c my_memmove.c my_memset.c my_strcat.c \
my_strchr.c my_strcmp.c my_strcpy.c my_strdup.c my_strlen.c my_strstr.c my_tolower.c my_toupper.c \

OBJ=$(SRC:.c=.o)

all
clean
fclean
re